------------------USERS----------------------

INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, NATIONALITY, CODE_NATIONALITY, USER_NAME, PASSWORD, DELETED) VALUES (1,'Jonathan', 'Bolatti', '28/08/2022', 'Argentina', 'AR', 'petmatches@mail.com', 'pet123', 0);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, NATIONALITY, CODE_NATIONALITY, USER_NAME, PASSWORD, DELETED) VALUES (2,'Leonel', 'Bolatti', '28/08/2022', 'Argentina', 'AR', 'petmatches@mail.com', 'pet123', 0);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, NATIONALITY, CODE_NATIONALITY, USER_NAME, PASSWORD, DELETED) VALUES (3,'Elias', 'Bolatti', '28/08/2022', 'Argentina', 'AR', 'petmatches@mail.com', 'pet123', 0);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, NATIONALITY, CODE_NATIONALITY, USER_NAME, PASSWORD, DELETED) VALUES (4,'Rosario', 'Bolatti', '28/08/2022', 'Argentina', 'AR', 'petmatches@mail.com', 'pet123', 0);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, NATIONALITY, CODE_NATIONALITY, USER_NAME, PASSWORD, DELETED) VALUES (5,'Miguel', 'Bolatti', '28/08/2022', 'Argentina', 'AR', 'petmatches@mail.com', 'pet123', 0);
